[versions]
kotlin = "2.4.10"
autotweaker = "0.2.0-alpha.3+92e1e122"
serialization = "1.11.0"
coroutines = "1.11.0"
autoService = "1.1.1"
slf4j = "2.0.18"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
toolgen = { id = "io.github.autotweaker.toolgen", version.ref = "autotweaker" }

[libraries]
autotweaker-api = { module = "io.github.autotweaker:api", version.ref = "autotweaker" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
